=== Jablu/Web-Development/6. Playing With XML/Employee.dtd
<!ELEMENT employees (employee*)>
  <!ELEMENT employee (ecode,ename,salary,deptid)>
  <!ELEMENT ecode (#PCDATA)>
  <!ELEMENT ename (#PCDATA)>
  <!ELEMENT salary (#PCDATA)>
  <!ELEMENT deptid (#PCDATA)>
  <!ATTLIST employee pid (p1|p2|p3) "p1">

=== Jablu/Web-Development/6. Playing With XML/Employee.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE employees SYSTEM "Employee.dtd">

<employees>
<employee pid="p1">
  <ecode>101</ecode>
  <ename>John Lenon</ename>
  <salary>100000</salary>
  <deptid>001</deptid>
</employee>
<employee pid="p2">
  <ecode>104</ecode>
  <ename>Ed Sheeran</ename>
  <salary>100000</salary>
  <deptid>001</deptid>
</employee>
<employee pid="p3">
  <ecode>102</ecode>
  <ename>John Legend</ename>
  <salary>100000</salary>
  <deptid>001</deptid>
</employee>
</employees>
